name=DevLab_VEML3328
version=1.2.0
author=UNIT Electronics
maintainer=UNIT Electronics
sentence=Arduino driver for the VEML3328 RGBCIR color sensor.
paragraph=
category=Sensors
url=https://github.com/UNIT-Electronics-MX/unit_devlab_veml3328_library
architectures=*
includes=DevLab_VEML3328.h
